# roles/vault_servers/tasks/install.yml
# Install Hashicorp Vault server.

# temp fix for: https://gitlab.alpinelinux.org/alpine/cloud/alpine-cloud-images/-/issues/160
- name: Temp fix | Manually set dns.
  ansible.builtin.shell:
    cmd: |
      cat << EOF > /etc/resolv.conf
      nameserver 10.10.10.21
      nameserver 10.10.10.22
      EOF
  when: ansible_facts.distribution in ["Alpine"]

- name: Temp fix | Restart networking.
  ansible.builtin.shell:
    cmd: rc-service networking restart
  when: ansible_facts.distribution in ["Alpine"]

# Install dependencies
- name: Install | Deps | Install dependencies APK.
  community.general.apk:
    name: "{{ vault_deps_apk }}"
    state: latest
    no_cache: true
  when: ansible_facts.distribution in ["Alpine"]

- name: Install | Deps | Install dependencies APT.
  ansible.builtin.apt:
    name: "{{ vault_deps_apt }}"
    state: latest
    update_cache: false
  when: ansible_facts.distribution in ["Debian", "Ubuntu"]

- name: Install | Deps | Install dependencies RPM.
  ansible.builtin.dnf:
    name: "{{ vault_deps_dnf }}"
    state: latest
    update_cache: true
  when: ansible_facts.distribution in ["Alma", "CentOS", "Fedora", "Rocky"]

- name: Install | Deps | Create vault group.
  ansible.builtin.group:
    name: vault
    state: present

- name: Install | Deps | Create vault user.
  ansible.builtin.user:
    name: vault
    group: vault
    shell: /sbin/nologin
    create_home: false
    password_lock: true
    state: present

- name: Install | Deps | Create application directories.
  ansible.builtin.file:
    path: "{{ item }}"
    owner: vault
    group: vault
    mode: 0775
    state: directory
  with_items:
    - /opt/lego
    - /etc/vault.d
    - /opt/vault/data
    - /opt/vault/tls
    - /var/log/vault

# Configure firewalld.
- name: Install | Firewall | Configure iptables rules.
  ansible.builtin.template:
    src: iptables.rules.j2
    dest: /etc/iptables/iptables.rules
    owner: root
    group: root
    mode: 0644
  notify: restart-iptables
  when: ansible_facts.distribution in ["Alpine", "Debian", "Ubuntu"]

- name: Install | Firewall | Load firewall rules.
  ansible.builtin.shell:
    cmd: iptables-restore < /etc/iptables/iptables.rules
  when: ansible_facts.distribution in ["Alpine", "Debian", "Ubuntu"]

- name: Install | Firewall | Write firewall rules to disk.
  ansible.builtin.command:
    cmd: rc-service iptables save
  when: ansible_facts.distribution in ["Alpine"]

- name: Install | Firewall | Enable iptables service.
  ansible.builtin.command:
    cmd: rc-update add iptables
  when: ansible_facts.distribution in ["Alpine"]

- name: Install | Firewall | Modify firewall default zone.
  ansible.posix.firewalld:
    zone: public
    service: "{{ item }}"
    state: enabled
    permanent: true
  loop:
    - https
  notify: restart-firewalld
  when: ansible_facts.distribution in ["Alma", "CentOS", "Fedora", "Rocky"]

- name: Install | Firewall | Add vault web ports.
  ansible.posix.firewalld:
    zone: public
    port: "{{ item }}"
    state: enabled
    permanent: true
  loop:
    - 8200/tcp #API port
    - 8201/tcp #Cluster port
    - 8125/tcp #Telemetry port
  notify: restart-firewalld
  when: ansible_facts.distribution in ["Alma", "CentOS", "Fedora", "Rocky"]

# Configure local DNS
- name: DNS | Replace cloud-init hosts file
  ansible.builtin.template:
    src: cloudinit-hosts.j2
    dest: "{{ dist_cloudinit_dest[ansible_facts.distribution] }}"
    owner: root
    group: root
    mode: 0640
  notify: restart-cloudinit

# Install and setup lego
- name: Install | lego | Get latest binary releases.
  ansible.builtin.uri:
    url: https://api.github.com/repos/go-acme/lego/releases/latest
    headers:
      #ref: https://docs.github.com/en/rest/using-the-rest-api/getting-started-with-the-rest-api?apiVersion=2026-03-10#accept
      Accept: "application/vnd.github+json"
    return_content: true
    method: GET
  register: lego_release

- name: Install | lego | Find latest linux_amd64 url.
  ansible.builtin.set_fact:
    lego_url: >-
      {{
        lego_release.json.assets
        | selectattr('name', 'search', 'linux_amd64\.tar\.gz$')
        | map(attribute='browser_download_url')
        | first
      }}

- name: Install | lego | Download binary package.
  ansible.builtin.get_url:
    url: "{{ lego_url }}"
    dest: /tmp/lego.tar.gz
    owner: root
    group: root
    mode: 0755

- name: Install | lego | Unzip binary.
  ansible.builtin.unarchive:
    src: /tmp/lego.tar.gz
    dest: /sbin/
    owner: root
    group: root
    mode: 0755
    remote_src: true

- name: Install | lego | Add config file.
  ansible.builtin.template:
    src: lego-config.yml.j2
    dest: /opt/lego/.lego.yml
    owner: vault
    group: vault
    mode: 0640

- name: Install | lego | Add env file.
  ansible.builtin.template:
    src: lego-env.yml.j2
    dest: /opt/lego/.env.cf
    owner: vault
    group: vault
    mode: 0640

- name: Install | lego | Run and get certs.
  ansible.builtin.shell:
    cmd: cd /opt/lego && lego && chown -R vault:vault /opt/lego

- name: Install | lego | Create cert update cron job.
  ansible.builtin.cron:
    user: vault
    name: "update certs"
    minute: "35"
    hour: "2"
    job: "cd /opt/lego && lego && chown -R vault:vault /opt/lego"

# Install vault
- name: Install | Vault | Get latest binary release.
  ansible.builtin.uri:
    url: https://api.releases.hashicorp.com/v1/releases/vault/latest?license_class=oss
    headers:
      Accept: "application/json"
    return_content: true
    method: GET
  register: vault_release

- name: Install | Vault | Set version and download url.
  ansible.builtin.set_fact:
    vault_version: "{{ vault_release.json.version }}"
    vault_url: "https://releases.hashicorp.com/vault/{{ vault_release.json.version }}/vault_{{ vault_release.json.version }}_linux_amd64.zip"

- name: Install | Vault | Download binary package.
  ansible.builtin.get_url:
    url: "{{ vault_url }}"
    dest: /tmp/vault.zip
    owner: root
    group: root
    mode: 0755

- name: Install | Vault | Unzip binary package.
  ansible.builtin.unarchive:
    src: /tmp/vault.zip
    dest: /usr/sbin
    owner: root
    group: root
    mode: 0755
    remote_src: true
  when: ansible_facts.distribution in ["Alpine"]

- name: Install | Vault | Copy openrc service file.
  ansible.builtin.copy:
    src: openrc-vault
    dest: /etc/init.d/vault
    owner: root
    group: root
    mode: 0755
  when: ansible_facts.distribution in ["Alpine"]

- name: Install | Vault | Import initial config file.
  ansible.builtin.template:
    src: vault-config.hcl.j2
    dest: /etc/vault.d/vault.hcl
    owner: vault
    group: vault
    mode: 0640
  notify: restart-vault

# Force handlers to run
- name: Install | Handlers | Force handlers to run.
  meta: flush_handlers
