# roles/vault_servers/tasks/setup-secrets.yml
# Setup KV secret engine and consul-template Vault UI.
# ref: https://medium.com/hashicorp-engineering/pki-as-a-service-with-hashicorp-vault-a8d075ece9a

# Enable KV Secrets Engine
- name: Secrets | KV | Enable KV Secrets Engine.
  ansible.builtin.uri:
    url: "https://{{ ansible_facts.fqdn }}:8200/v1/sys/mounts/secrets-v2"
    headers:
      X-Vault-Token: "{{ vault_root_token }}"
    body:
      type: "kv"
      description: "Production KV Secrets Engine"
      options:
        version: 2
    body_format: json
    method: POST
    validate_certs: false
    status_code:
      - 200
      - 204

# Load all secrets into Vault
- name: Secrets | KV | Loading all secrets into Vault.
  ansible.builtin.uri:
    url: "https://{{ ansible_facts.fqdn }}:8200/v1/secrets-v2/data/{{ item.key }}"
    headers:
      X-Vault-Token: "{{ vault_root_token }}"
    body:
      data: "{{ item.value }}"
    body_format: json
    method: POST
    validate_certs: false
    status_code:
      - 200
      - 204
  loop: "{{ vault_kv | dict2items }}"

- name: Secrets | Services | Restart Vault service.
  ansible.builtin.service:
    name: vault
    state: restarted
    enabled: true

# Vault is picky about restarting too quickly
- name: Secrets | Services | Restart services cooldown.
  ansible.builtin.pause:
    seconds: 20
