# Master deployment playbook for all servers on fresh site.
# Adjust this for RKE/Swarm deployment type.

# Config and deploy DNS servers
- name: Deploy | Run DNS role.
  hosts: dns_servers
  become: true
  roles:
    - dns_servers

# Config and deploy Vault server
- name: Deploy | Run Vault role.
  hosts: vault_servers
  become: true
  roles:
    - vault_servers

# Deploy all Vault PKI certificates
- name: Deploy | Run PKI role.
  hosts: all
  become: true
  roles:
    - pki_issue

# Update and reboot all servers
- name: Deploy | Run Base role.
  hosts: all
  become: true
  roles:
    - base
