# Used for emergency security patches for all servers.

# Update Swarm apps
- name: Updates | Run Swarm Apps role.
  hosts: swarm_servers
  become: true
  roles:
    - swarm_apps

# Base updates for servers, dns, and vault
- name: Updates | Run Base updates role.
  hosts: all
  become: true
  roles:
    - base
