# roles/dns_servers/vars/main.yml
# All ADGuardHome variables.

vault_secrets_dir: /home/dbegin/build/secrets

# APK dependencies
adguard_deps_apk:
  - curl
  - iptables
  - openssl
  - tar
  - unbound
  - unzip

# APT dependencies
adguard_deps_apt:
  - curl
  - iptables
  - openssl
  - tar
  - unbound
  - unzip

# RPM dependencies
adguard_deps_dnf:
  - curl
  - firewalld
  - openssl
  - tar
  - unbound
  - unzip

# Distro variables
dist_cloudinit_dest:
  Alpine: /etc/cloud/templates/hosts.alpine.tmpl
  Debian: /etc/cloud/templates/hosts.debian.tmpl
  Ubuntu: /etc/cloud/templates/hosts.debian.tmpl
  Alma: /etc/cloud/templates/hosts.redhat.tmpl
  CentOS: /etc/cloud/templates/hosts.redhat.tmpl
  Fedora: /etc/cloud/templates/hosts.redhat.tmpl
  Rocky: /etc/cloud/templates/hosts.redhat.tmpl

# iptables allow ports
inbound_udp_allow:
  - 53   #dns
  - 67   #dhcp server
  - 68   #dhcp client
inbound_tcp_allow:
  - 22   #ssh
  - 443  #https
  - 853  #dns over tls
  - 3000 #adguard web
