# roles/vault_servers/vars/main.yml
# All vault variables.

vault_secrets_dir: /home/dbegin/build/secrets

#Vault APK dependencies
vault_deps_apk:
  - ca-certificates
  - curl
  - iptables
  - jq
  - py3-cryptography
  - openssl
  - tar
  - unzip

# Vault APT dependencies
vault_deps_apt:
  - ca-certificates
  - iptables
  - jq
  - openssl
  - tar
  - unzip
  - vault

# Vault RPM dependencies
vault_deps_dnf:
  - ca-certificates
  - firewalld
  - jq
  - openssl
  - tar
  - unzip
  - vault

# Distro variables
dist_cloudinit_dest:
  Alpine: /etc/cloud/templates/hosts.alpine.tmpl
  Debian: /etc/cloud/templates/hosts.debian.tmpl
  Ubuntu: /etc/cloud/templates/hosts.debian.tmpl
  Alma: /etc/cloud/templates/hosts.redhat.tmpl
  CentOS: /etc/cloud/templates/hosts.redhat.tmpl
  Fedora: /etc/cloud/templates/hosts.redhat.tmpl
  Rocky: /etc/cloud/templates/hosts.redhat.tmpl

# iptables allow ports
inbound_udp_allow:
  - 8200 #vault api
inbound_tcp_allow:
  - 22   #ssh
  - 443  #https
  - 8200 #vault api
  - 8201 #vault cluster
  - 8125 #vault telementry

# Vault config vars
vault_log_level: info

# Vault policies
vault_policy:
  - name: secrets-rw
    hcl: |
      path "sys/mounts" {
        capabilities = [ "read" ]
      }
      path "secrets*" {
        capabilities = [ "create", "read", "update", "delete", "list" ]
      }
      path "sys/policies/acl/*" {
        capabilities = [ "create", "read", "update", "delete", "list" ]
      }
      path "auth/token/create" {
          capabilities = [ "create", "update", "sudo" ]
      }
