# roles/swarm_apps/tasks/apps.yml
# Ensure dependencies are installed/updated.

# Deploy stacks
- name: Swarm Apps | Deploy | Deploy all apps.
  community.docker.docker_stack:
    name: prod
    state: present
    compose: '{{ ansible_path }}/roles/swarm_apps/files/compose.yml'

- name: Apps | Wait for rollout.
  ansible.builtin.pause:
    seconds: 5

# Prune server
- name: Swarm Apps | Deploy | Prune everything.
  ansible.builtin.shell:
    cmd: docker system prune --all --volumes --force
