# roles/swarm_apps/tasks/deps.yml
# Ensure dependencies are installed/updated.

# Ensure pip dependencies are installed
- name: Swarm Apps | pip | Install package APK.
  community.general.apk:
    name: py3-pip
    state: latest
    no_cache: true

- name: Swarm Apps | pip | Install Python packages.
  ansible.builtin.shell:
    cmd: pip install --break-system-packages jsondiff pyyaml

- name: Swarm Apps | Deps | Create app dirs.
  ansible.builtin.file:
    path: '{{ item }}'
    owner: 1000
    group: 1000
    mode: 0775
    state: directory
  with_items:
    - /opt/git
    - /opt/postgres
    - /opt/traefik

# Create Traefik templates
- name: Swarm Apps | Deps | Traefik template.
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: /opt/traefik/traefik.yml
    owner: 1000
    group: 1000
    mode: 0644

- name: Swarm Apps | Deps | Traefik config template.
  ansible.builtin.template:
    src: config.yml.j2
    dest: /opt/traefik/config.yml
    owner: 1000
    group: 1000
    mode: 0644
