# roles/base/tasks/updates-dns.yml
# Update all DNS configurations.

# Include variables
- name: Import | Include variable files.
  ansible.builtin.include_vars:
    dir: '{{ ansible_path }}/roles/dns_servers/vars'

# Update unbound configuration
- name: DNS | unbound | Update root hints file.
  ansible.builtin.get_url:
    url: https://www.internic.net/domain/named.root
    dest: /etc/unbound/root.hints
    owner: root
    group: root
    mode: 0664

- name: DNS | unbound | Update config file.
  ansible.builtin.template:
    src: '{{ ansible_path }}/roles/dns_servers/templates/unbound.conf.j2'
    dest: /etc/unbound/unbound.conf
    owner: unbound
    group: unbound
    mode: 0640

# Update adguard configuration
- name: DNS | adguard | Update config file.
  ansible.builtin.template:
    src: '{{ ansible_path }}/roles/dns_servers/templates/adguard-config.yaml.j2'
    dest: /opt/AdGuardHome/AdGuardHome.yaml
    owner: root
    group: root
    mode: 0640
