# roles/base/tasks/updates-vault.yml
# Update all Vault configurations.

# Include variables
- name: Import | Include variable files.
  ansible.builtin.include_vars:
    dir: '{{ ansible_path }}/roles/vault_servers/vars'

- name: Import | Include secrets-rw token variable.
  ansible.builtin.slurp:
    src: "/home/{{ local_user }}/vault-token-root"
  register: vault_root_token
  delegate_to: localhost

# Load all secrets into Vault
- name: Vault | Loading all secrets into Vault.
  ansible.builtin.uri:
    url: "https://{{ ansible_fqdn }}:8200/v1/secrets-v2/data/{{ item.key }}"
    headers:
      X-Vault-Token: "{{ vault_root_token }}"
    body:
      data: "{{ item.value }}"
    body_format: json
    method: POST
    validate_certs: false
    status_code:
      - 200
      - 204
  loop: "{{ vault_kv | dict2items }}"
